//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Latte.g4 by ANTLR 4.7.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace LatteAntlr {
using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="LatteParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.2")]
[System.CLSCompliant(false)]
public interface ILatteListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="LatteParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProgram([NotNull] LatteParser.ProgramContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LatteParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProgram([NotNull] LatteParser.ProgramContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>functionDef</c>
	/// labeled alternative in <see cref="LatteParser.topDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctionDef([NotNull] LatteParser.FunctionDefContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>functionDef</c>
	/// labeled alternative in <see cref="LatteParser.topDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctionDef([NotNull] LatteParser.FunctionDefContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>classDef</c>
	/// labeled alternative in <see cref="LatteParser.topDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClassDef([NotNull] LatteParser.ClassDefContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>classDef</c>
	/// labeled alternative in <see cref="LatteParser.topDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClassDef([NotNull] LatteParser.ClassDefContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LatteParser.fieldOrMethodDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFieldOrMethodDef([NotNull] LatteParser.FieldOrMethodDefContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LatteParser.fieldOrMethodDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFieldOrMethodDef([NotNull] LatteParser.FieldOrMethodDefContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LatteParser.fieldDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFieldDef([NotNull] LatteParser.FieldDefContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LatteParser.fieldDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFieldDef([NotNull] LatteParser.FieldDefContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LatteParser.methodDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMethodDef([NotNull] LatteParser.MethodDefContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LatteParser.methodDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMethodDef([NotNull] LatteParser.MethodDefContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LatteParser.arg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArg([NotNull] LatteParser.ArgContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LatteParser.arg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArg([NotNull] LatteParser.ArgContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LatteParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBlock([NotNull] LatteParser.BlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LatteParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBlock([NotNull] LatteParser.BlockContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>Empty</c>
	/// labeled alternative in <see cref="LatteParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEmpty([NotNull] LatteParser.EmptyContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>Empty</c>
	/// labeled alternative in <see cref="LatteParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEmpty([NotNull] LatteParser.EmptyContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>BlockStmt</c>
	/// labeled alternative in <see cref="LatteParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBlockStmt([NotNull] LatteParser.BlockStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>BlockStmt</c>
	/// labeled alternative in <see cref="LatteParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBlockStmt([NotNull] LatteParser.BlockStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>Decl</c>
	/// labeled alternative in <see cref="LatteParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDecl([NotNull] LatteParser.DeclContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>Decl</c>
	/// labeled alternative in <see cref="LatteParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDecl([NotNull] LatteParser.DeclContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>Ass</c>
	/// labeled alternative in <see cref="LatteParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAss([NotNull] LatteParser.AssContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>Ass</c>
	/// labeled alternative in <see cref="LatteParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAss([NotNull] LatteParser.AssContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>StructAss</c>
	/// labeled alternative in <see cref="LatteParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStructAss([NotNull] LatteParser.StructAssContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>StructAss</c>
	/// labeled alternative in <see cref="LatteParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStructAss([NotNull] LatteParser.StructAssContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>Incr</c>
	/// labeled alternative in <see cref="LatteParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIncr([NotNull] LatteParser.IncrContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>Incr</c>
	/// labeled alternative in <see cref="LatteParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIncr([NotNull] LatteParser.IncrContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>Decr</c>
	/// labeled alternative in <see cref="LatteParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDecr([NotNull] LatteParser.DecrContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>Decr</c>
	/// labeled alternative in <see cref="LatteParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDecr([NotNull] LatteParser.DecrContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>StructIncr</c>
	/// labeled alternative in <see cref="LatteParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStructIncr([NotNull] LatteParser.StructIncrContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>StructIncr</c>
	/// labeled alternative in <see cref="LatteParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStructIncr([NotNull] LatteParser.StructIncrContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>StructDecr</c>
	/// labeled alternative in <see cref="LatteParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStructDecr([NotNull] LatteParser.StructDecrContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>StructDecr</c>
	/// labeled alternative in <see cref="LatteParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStructDecr([NotNull] LatteParser.StructDecrContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>Ret</c>
	/// labeled alternative in <see cref="LatteParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRet([NotNull] LatteParser.RetContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>Ret</c>
	/// labeled alternative in <see cref="LatteParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRet([NotNull] LatteParser.RetContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>VRet</c>
	/// labeled alternative in <see cref="LatteParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVRet([NotNull] LatteParser.VRetContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>VRet</c>
	/// labeled alternative in <see cref="LatteParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVRet([NotNull] LatteParser.VRetContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>Cond</c>
	/// labeled alternative in <see cref="LatteParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCond([NotNull] LatteParser.CondContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>Cond</c>
	/// labeled alternative in <see cref="LatteParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCond([NotNull] LatteParser.CondContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>CondElse</c>
	/// labeled alternative in <see cref="LatteParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCondElse([NotNull] LatteParser.CondElseContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>CondElse</c>
	/// labeled alternative in <see cref="LatteParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCondElse([NotNull] LatteParser.CondElseContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>While</c>
	/// labeled alternative in <see cref="LatteParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWhile([NotNull] LatteParser.WhileContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>While</c>
	/// labeled alternative in <see cref="LatteParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWhile([NotNull] LatteParser.WhileContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>SExp</c>
	/// labeled alternative in <see cref="LatteParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSExp([NotNull] LatteParser.SExpContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>SExp</c>
	/// labeled alternative in <see cref="LatteParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSExp([NotNull] LatteParser.SExpContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>TTypeName</c>
	/// labeled alternative in <see cref="LatteParser.type_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTTypeName([NotNull] LatteParser.TTypeNameContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>TTypeName</c>
	/// labeled alternative in <see cref="LatteParser.type_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTTypeName([NotNull] LatteParser.TTypeNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LatteParser.item"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterItem([NotNull] LatteParser.ItemContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LatteParser.item"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitItem([NotNull] LatteParser.ItemContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>EId</c>
	/// labeled alternative in <see cref="LatteParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEId([NotNull] LatteParser.EIdContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>EId</c>
	/// labeled alternative in <see cref="LatteParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEId([NotNull] LatteParser.EIdContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>EFunCall</c>
	/// labeled alternative in <see cref="LatteParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEFunCall([NotNull] LatteParser.EFunCallContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>EFunCall</c>
	/// labeled alternative in <see cref="LatteParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEFunCall([NotNull] LatteParser.EFunCallContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ERelOp</c>
	/// labeled alternative in <see cref="LatteParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterERelOp([NotNull] LatteParser.ERelOpContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ERelOp</c>
	/// labeled alternative in <see cref="LatteParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitERelOp([NotNull] LatteParser.ERelOpContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ETrue</c>
	/// labeled alternative in <see cref="LatteParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterETrue([NotNull] LatteParser.ETrueContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ETrue</c>
	/// labeled alternative in <see cref="LatteParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitETrue([NotNull] LatteParser.ETrueContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ECast</c>
	/// labeled alternative in <see cref="LatteParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterECast([NotNull] LatteParser.ECastContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ECast</c>
	/// labeled alternative in <see cref="LatteParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitECast([NotNull] LatteParser.ECastContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>EOr</c>
	/// labeled alternative in <see cref="LatteParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEOr([NotNull] LatteParser.EOrContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>EOr</c>
	/// labeled alternative in <see cref="LatteParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEOr([NotNull] LatteParser.EOrContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>EInt</c>
	/// labeled alternative in <see cref="LatteParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEInt([NotNull] LatteParser.EIntContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>EInt</c>
	/// labeled alternative in <see cref="LatteParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEInt([NotNull] LatteParser.EIntContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>EUnOp</c>
	/// labeled alternative in <see cref="LatteParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEUnOp([NotNull] LatteParser.EUnOpContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>EUnOp</c>
	/// labeled alternative in <see cref="LatteParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEUnOp([NotNull] LatteParser.EUnOpContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>EStr</c>
	/// labeled alternative in <see cref="LatteParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEStr([NotNull] LatteParser.EStrContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>EStr</c>
	/// labeled alternative in <see cref="LatteParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEStr([NotNull] LatteParser.EStrContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>EMulOp</c>
	/// labeled alternative in <see cref="LatteParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEMulOp([NotNull] LatteParser.EMulOpContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>EMulOp</c>
	/// labeled alternative in <see cref="LatteParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEMulOp([NotNull] LatteParser.EMulOpContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>EAnd</c>
	/// labeled alternative in <see cref="LatteParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEAnd([NotNull] LatteParser.EAndContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>EAnd</c>
	/// labeled alternative in <see cref="LatteParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEAnd([NotNull] LatteParser.EAndContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>EMethodCall</c>
	/// labeled alternative in <see cref="LatteParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEMethodCall([NotNull] LatteParser.EMethodCallContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>EMethodCall</c>
	/// labeled alternative in <see cref="LatteParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEMethodCall([NotNull] LatteParser.EMethodCallContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>EObjectField</c>
	/// labeled alternative in <see cref="LatteParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEObjectField([NotNull] LatteParser.EObjectFieldContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>EObjectField</c>
	/// labeled alternative in <see cref="LatteParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEObjectField([NotNull] LatteParser.EObjectFieldContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>EParen</c>
	/// labeled alternative in <see cref="LatteParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEParen([NotNull] LatteParser.EParenContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>EParen</c>
	/// labeled alternative in <see cref="LatteParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEParen([NotNull] LatteParser.EParenContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>EFalse</c>
	/// labeled alternative in <see cref="LatteParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEFalse([NotNull] LatteParser.EFalseContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>EFalse</c>
	/// labeled alternative in <see cref="LatteParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEFalse([NotNull] LatteParser.EFalseContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>EAddOp</c>
	/// labeled alternative in <see cref="LatteParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEAddOp([NotNull] LatteParser.EAddOpContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>EAddOp</c>
	/// labeled alternative in <see cref="LatteParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEAddOp([NotNull] LatteParser.EAddOpContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ENull</c>
	/// labeled alternative in <see cref="LatteParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterENull([NotNull] LatteParser.ENullContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ENull</c>
	/// labeled alternative in <see cref="LatteParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitENull([NotNull] LatteParser.ENullContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ENewObject</c>
	/// labeled alternative in <see cref="LatteParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterENewObject([NotNull] LatteParser.ENewObjectContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ENewObject</c>
	/// labeled alternative in <see cref="LatteParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitENewObject([NotNull] LatteParser.ENewObjectContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>UnaryMinus</c>
	/// labeled alternative in <see cref="LatteParser.unOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnaryMinus([NotNull] LatteParser.UnaryMinusContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>UnaryMinus</c>
	/// labeled alternative in <see cref="LatteParser.unOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnaryMinus([NotNull] LatteParser.UnaryMinusContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>UnaryNeg</c>
	/// labeled alternative in <see cref="LatteParser.unOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnaryNeg([NotNull] LatteParser.UnaryNegContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>UnaryNeg</c>
	/// labeled alternative in <see cref="LatteParser.unOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnaryNeg([NotNull] LatteParser.UnaryNegContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>Plus</c>
	/// labeled alternative in <see cref="LatteParser.addOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPlus([NotNull] LatteParser.PlusContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>Plus</c>
	/// labeled alternative in <see cref="LatteParser.addOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPlus([NotNull] LatteParser.PlusContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>Minus</c>
	/// labeled alternative in <see cref="LatteParser.addOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMinus([NotNull] LatteParser.MinusContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>Minus</c>
	/// labeled alternative in <see cref="LatteParser.addOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMinus([NotNull] LatteParser.MinusContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>Multiply</c>
	/// labeled alternative in <see cref="LatteParser.mulOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMultiply([NotNull] LatteParser.MultiplyContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>Multiply</c>
	/// labeled alternative in <see cref="LatteParser.mulOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMultiply([NotNull] LatteParser.MultiplyContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>Divide</c>
	/// labeled alternative in <see cref="LatteParser.mulOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDivide([NotNull] LatteParser.DivideContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>Divide</c>
	/// labeled alternative in <see cref="LatteParser.mulOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDivide([NotNull] LatteParser.DivideContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>Modulo</c>
	/// labeled alternative in <see cref="LatteParser.mulOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterModulo([NotNull] LatteParser.ModuloContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>Modulo</c>
	/// labeled alternative in <see cref="LatteParser.mulOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitModulo([NotNull] LatteParser.ModuloContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>LessThan</c>
	/// labeled alternative in <see cref="LatteParser.relOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLessThan([NotNull] LatteParser.LessThanContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>LessThan</c>
	/// labeled alternative in <see cref="LatteParser.relOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLessThan([NotNull] LatteParser.LessThanContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>LessEquals</c>
	/// labeled alternative in <see cref="LatteParser.relOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLessEquals([NotNull] LatteParser.LessEqualsContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>LessEquals</c>
	/// labeled alternative in <see cref="LatteParser.relOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLessEquals([NotNull] LatteParser.LessEqualsContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>GreaterThan</c>
	/// labeled alternative in <see cref="LatteParser.relOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGreaterThan([NotNull] LatteParser.GreaterThanContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>GreaterThan</c>
	/// labeled alternative in <see cref="LatteParser.relOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGreaterThan([NotNull] LatteParser.GreaterThanContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>GreaterEquals</c>
	/// labeled alternative in <see cref="LatteParser.relOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGreaterEquals([NotNull] LatteParser.GreaterEqualsContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>GreaterEquals</c>
	/// labeled alternative in <see cref="LatteParser.relOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGreaterEquals([NotNull] LatteParser.GreaterEqualsContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>Equals</c>
	/// labeled alternative in <see cref="LatteParser.relOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEquals([NotNull] LatteParser.EqualsContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>Equals</c>
	/// labeled alternative in <see cref="LatteParser.relOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEquals([NotNull] LatteParser.EqualsContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>NotEquals</c>
	/// labeled alternative in <see cref="LatteParser.relOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNotEquals([NotNull] LatteParser.NotEqualsContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>NotEquals</c>
	/// labeled alternative in <see cref="LatteParser.relOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNotEquals([NotNull] LatteParser.NotEqualsContext context);
}
} // namespace LatteAntlr
