//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Latte.g4 by ANTLR 4.7.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace LatteAntlr {
using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.2")]
[System.CLSCompliant(false)]
public partial class LatteParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, T__2=3, T__3=4, T__4=5, T__5=6, T__6=7, T__7=8, T__8=9, 
		T__9=10, T__10=11, T__11=12, T__12=13, T__13=14, T__14=15, T__15=16, T__16=17, 
		T__17=18, T__18=19, T__19=20, T__20=21, T__21=22, T__22=23, T__23=24, 
		T__24=25, T__25=26, T__26=27, T__27=28, T__28=29, T__29=30, T__30=31, 
		T__31=32, T__32=33, COMMENT=34, MULTICOMMENT=35, INT=36, ID=37, WS=38, 
		STR=39;
	public const int
		RULE_program = 0, RULE_topDef = 1, RULE_fieldDef = 2, RULE_arg = 3, RULE_block = 4, 
		RULE_stmt = 5, RULE_type_ = 6, RULE_item = 7, RULE_expr = 8, RULE_unOp = 9, 
		RULE_addOp = 10, RULE_mulOp = 11, RULE_relOp = 12;
	public static readonly string[] ruleNames = {
		"program", "topDef", "fieldDef", "arg", "block", "stmt", "type_", "item", 
		"expr", "unOp", "addOp", "mulOp", "relOp"
	};

	private static readonly string[] _LiteralNames = {
		null, "'('", "')'", "'class'", "'{'", "'}'", "';'", "','", "'='", "'.'", 
		"'++'", "'--'", "'return'", "'if'", "'else'", "'while'", "'&&'", "'||'", 
		"'true'", "'false'", "'null'", "'new'", "'-'", "'!'", "'+'", "'*'", "'/'", 
		"'%'", "'<'", "'<='", "'>'", "'>='", "'=='", "'!='"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, null, null, null, null, null, null, null, null, 
		null, null, null, null, null, null, null, null, null, null, null, null, 
		null, null, null, null, null, null, null, null, null, null, "COMMENT", 
		"MULTICOMMENT", "INT", "ID", "WS", "STR"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "Latte.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static LatteParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

		public LatteParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public LatteParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	public partial class ProgramContext : ParserRuleContext {
		public TopDefContext[] topDef() {
			return GetRuleContexts<TopDefContext>();
		}
		public TopDefContext topDef(int i) {
			return GetRuleContext<TopDefContext>(i);
		}
		public ProgramContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_program; } }
		public override void EnterRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.EnterProgram(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.ExitProgram(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ILatteVisitor<TResult> typedVisitor = visitor as ILatteVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitProgram(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ProgramContext program() {
		ProgramContext _localctx = new ProgramContext(Context, State);
		EnterRule(_localctx, 0, RULE_program);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 27;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			do {
				{
				{
				State = 26; topDef();
				}
				}
				State = 29;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			} while ( _la==T__2 || _la==ID );
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class TopDefContext : ParserRuleContext {
		public TopDefContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_topDef; } }
	 
		public TopDefContext() { }
		public virtual void CopyFrom(TopDefContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class FunctionDefContext : TopDefContext {
		public Type_Context type_() {
			return GetRuleContext<Type_Context>(0);
		}
		public ITerminalNode ID() { return GetToken(LatteParser.ID, 0); }
		public BlockContext block() {
			return GetRuleContext<BlockContext>(0);
		}
		public ArgContext arg() {
			return GetRuleContext<ArgContext>(0);
		}
		public FunctionDefContext(TopDefContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.EnterFunctionDef(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.ExitFunctionDef(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ILatteVisitor<TResult> typedVisitor = visitor as ILatteVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFunctionDef(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class ClassDefContext : TopDefContext {
		public ITerminalNode ID() { return GetToken(LatteParser.ID, 0); }
		public FieldDefContext[] fieldDef() {
			return GetRuleContexts<FieldDefContext>();
		}
		public FieldDefContext fieldDef(int i) {
			return GetRuleContext<FieldDefContext>(i);
		}
		public ClassDefContext(TopDefContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.EnterClassDef(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.ExitClassDef(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ILatteVisitor<TResult> typedVisitor = visitor as ILatteVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitClassDef(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public TopDefContext topDef() {
		TopDefContext _localctx = new TopDefContext(Context, State);
		EnterRule(_localctx, 2, RULE_topDef);
		int _la;
		try {
			State = 50;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case ID:
				_localctx = new FunctionDefContext(_localctx);
				EnterOuterAlt(_localctx, 1);
				{
				State = 31; type_();
				State = 32; Match(ID);
				State = 33; Match(T__0);
				State = 35;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if (_la==ID) {
					{
					State = 34; arg();
					}
				}

				State = 37; Match(T__1);
				State = 38; block();
				}
				break;
			case T__2:
				_localctx = new ClassDefContext(_localctx);
				EnterOuterAlt(_localctx, 2);
				{
				State = 40; Match(T__2);
				State = 41; Match(ID);
				State = 42; Match(T__3);
				State = 46;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				while (_la==ID) {
					{
					{
					State = 43; fieldDef();
					}
					}
					State = 48;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				}
				State = 49; Match(T__4);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class FieldDefContext : ParserRuleContext {
		public Type_Context type_() {
			return GetRuleContext<Type_Context>(0);
		}
		public ITerminalNode ID() { return GetToken(LatteParser.ID, 0); }
		public FieldDefContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_fieldDef; } }
		public override void EnterRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.EnterFieldDef(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.ExitFieldDef(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ILatteVisitor<TResult> typedVisitor = visitor as ILatteVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFieldDef(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public FieldDefContext fieldDef() {
		FieldDefContext _localctx = new FieldDefContext(Context, State);
		EnterRule(_localctx, 4, RULE_fieldDef);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 52; type_();
			State = 53; Match(ID);
			State = 54; Match(T__5);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ArgContext : ParserRuleContext {
		public Type_Context[] type_() {
			return GetRuleContexts<Type_Context>();
		}
		public Type_Context type_(int i) {
			return GetRuleContext<Type_Context>(i);
		}
		public ITerminalNode[] ID() { return GetTokens(LatteParser.ID); }
		public ITerminalNode ID(int i) {
			return GetToken(LatteParser.ID, i);
		}
		public ArgContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_arg; } }
		public override void EnterRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.EnterArg(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.ExitArg(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ILatteVisitor<TResult> typedVisitor = visitor as ILatteVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitArg(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ArgContext arg() {
		ArgContext _localctx = new ArgContext(Context, State);
		EnterRule(_localctx, 6, RULE_arg);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 56; type_();
			State = 57; Match(ID);
			State = 64;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==T__6) {
				{
				{
				State = 58; Match(T__6);
				State = 59; type_();
				State = 60; Match(ID);
				}
				}
				State = 66;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class BlockContext : ParserRuleContext {
		public StmtContext[] stmt() {
			return GetRuleContexts<StmtContext>();
		}
		public StmtContext stmt(int i) {
			return GetRuleContext<StmtContext>(i);
		}
		public BlockContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_block; } }
		public override void EnterRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.EnterBlock(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.ExitBlock(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ILatteVisitor<TResult> typedVisitor = visitor as ILatteVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitBlock(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public BlockContext block() {
		BlockContext _localctx = new BlockContext(Context, State);
		EnterRule(_localctx, 8, RULE_block);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 67; Match(T__3);
			State = 71;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << T__0) | (1L << T__3) | (1L << T__5) | (1L << T__11) | (1L << T__12) | (1L << T__14) | (1L << T__17) | (1L << T__18) | (1L << T__19) | (1L << T__20) | (1L << T__21) | (1L << T__22) | (1L << INT) | (1L << ID) | (1L << STR))) != 0)) {
				{
				{
				State = 68; stmt();
				}
				}
				State = 73;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 74; Match(T__4);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class StmtContext : ParserRuleContext {
		public StmtContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_stmt; } }
	 
		public StmtContext() { }
		public virtual void CopyFrom(StmtContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class AssContext : StmtContext {
		public ITerminalNode ID() { return GetToken(LatteParser.ID, 0); }
		public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		public AssContext(StmtContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.EnterAss(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.ExitAss(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ILatteVisitor<TResult> typedVisitor = visitor as ILatteVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAss(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class RetContext : StmtContext {
		public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		public RetContext(StmtContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.EnterRet(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.ExitRet(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ILatteVisitor<TResult> typedVisitor = visitor as ILatteVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitRet(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class StructAssContext : StmtContext {
		public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		public ITerminalNode ID() { return GetToken(LatteParser.ID, 0); }
		public StructAssContext(StmtContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.EnterStructAss(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.ExitStructAss(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ILatteVisitor<TResult> typedVisitor = visitor as ILatteVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitStructAss(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class CondContext : StmtContext {
		public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		public StmtContext stmt() {
			return GetRuleContext<StmtContext>(0);
		}
		public CondContext(StmtContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.EnterCond(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.ExitCond(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ILatteVisitor<TResult> typedVisitor = visitor as ILatteVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitCond(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class CondElseContext : StmtContext {
		public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		public StmtContext[] stmt() {
			return GetRuleContexts<StmtContext>();
		}
		public StmtContext stmt(int i) {
			return GetRuleContext<StmtContext>(i);
		}
		public CondElseContext(StmtContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.EnterCondElse(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.ExitCondElse(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ILatteVisitor<TResult> typedVisitor = visitor as ILatteVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitCondElse(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class VRetContext : StmtContext {
		public VRetContext(StmtContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.EnterVRet(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.ExitVRet(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ILatteVisitor<TResult> typedVisitor = visitor as ILatteVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitVRet(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class BlockStmtContext : StmtContext {
		public BlockContext block() {
			return GetRuleContext<BlockContext>(0);
		}
		public BlockStmtContext(StmtContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.EnterBlockStmt(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.ExitBlockStmt(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ILatteVisitor<TResult> typedVisitor = visitor as ILatteVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitBlockStmt(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class DeclContext : StmtContext {
		public Type_Context type_() {
			return GetRuleContext<Type_Context>(0);
		}
		public ItemContext[] item() {
			return GetRuleContexts<ItemContext>();
		}
		public ItemContext item(int i) {
			return GetRuleContext<ItemContext>(i);
		}
		public DeclContext(StmtContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.EnterDecl(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.ExitDecl(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ILatteVisitor<TResult> typedVisitor = visitor as ILatteVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitDecl(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class WhileContext : StmtContext {
		public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		public StmtContext stmt() {
			return GetRuleContext<StmtContext>(0);
		}
		public WhileContext(StmtContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.EnterWhile(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.ExitWhile(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ILatteVisitor<TResult> typedVisitor = visitor as ILatteVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitWhile(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class SExpContext : StmtContext {
		public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		public SExpContext(StmtContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.EnterSExp(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.ExitSExp(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ILatteVisitor<TResult> typedVisitor = visitor as ILatteVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitSExp(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class DecrContext : StmtContext {
		public ITerminalNode ID() { return GetToken(LatteParser.ID, 0); }
		public DecrContext(StmtContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.EnterDecr(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.ExitDecr(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ILatteVisitor<TResult> typedVisitor = visitor as ILatteVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitDecr(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class EmptyContext : StmtContext {
		public EmptyContext(StmtContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.EnterEmpty(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.ExitEmpty(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ILatteVisitor<TResult> typedVisitor = visitor as ILatteVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitEmpty(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class IncrContext : StmtContext {
		public ITerminalNode ID() { return GetToken(LatteParser.ID, 0); }
		public IncrContext(StmtContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.EnterIncr(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.ExitIncr(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ILatteVisitor<TResult> typedVisitor = visitor as ILatteVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitIncr(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public StmtContext stmt() {
		StmtContext _localctx = new StmtContext(Context, State);
		EnterRule(_localctx, 10, RULE_stmt);
		int _la;
		try {
			State = 136;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,7,Context) ) {
			case 1:
				_localctx = new EmptyContext(_localctx);
				EnterOuterAlt(_localctx, 1);
				{
				State = 76; Match(T__5);
				}
				break;
			case 2:
				_localctx = new BlockStmtContext(_localctx);
				EnterOuterAlt(_localctx, 2);
				{
				State = 77; block();
				}
				break;
			case 3:
				_localctx = new DeclContext(_localctx);
				EnterOuterAlt(_localctx, 3);
				{
				State = 78; type_();
				State = 79; item();
				State = 84;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				while (_la==T__6) {
					{
					{
					State = 80; Match(T__6);
					State = 81; item();
					}
					}
					State = 86;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				}
				State = 87; Match(T__5);
				}
				break;
			case 4:
				_localctx = new AssContext(_localctx);
				EnterOuterAlt(_localctx, 4);
				{
				State = 89; Match(ID);
				State = 90; Match(T__7);
				State = 91; expr(0);
				State = 92; Match(T__5);
				}
				break;
			case 5:
				_localctx = new StructAssContext(_localctx);
				EnterOuterAlt(_localctx, 5);
				{
				State = 94; expr(0);
				State = 95; Match(T__8);
				State = 96; Match(ID);
				State = 97; Match(T__7);
				State = 98; expr(0);
				State = 99; Match(T__5);
				}
				break;
			case 6:
				_localctx = new IncrContext(_localctx);
				EnterOuterAlt(_localctx, 6);
				{
				State = 101; Match(ID);
				State = 102; Match(T__9);
				State = 103; Match(T__5);
				}
				break;
			case 7:
				_localctx = new DecrContext(_localctx);
				EnterOuterAlt(_localctx, 7);
				{
				State = 104; Match(ID);
				State = 105; Match(T__10);
				State = 106; Match(T__5);
				}
				break;
			case 8:
				_localctx = new RetContext(_localctx);
				EnterOuterAlt(_localctx, 8);
				{
				State = 107; Match(T__11);
				State = 108; expr(0);
				State = 109; Match(T__5);
				}
				break;
			case 9:
				_localctx = new VRetContext(_localctx);
				EnterOuterAlt(_localctx, 9);
				{
				State = 111; Match(T__11);
				State = 112; Match(T__5);
				}
				break;
			case 10:
				_localctx = new CondContext(_localctx);
				EnterOuterAlt(_localctx, 10);
				{
				State = 113; Match(T__12);
				State = 114; Match(T__0);
				State = 115; expr(0);
				State = 116; Match(T__1);
				State = 117; stmt();
				}
				break;
			case 11:
				_localctx = new CondElseContext(_localctx);
				EnterOuterAlt(_localctx, 11);
				{
				State = 119; Match(T__12);
				State = 120; Match(T__0);
				State = 121; expr(0);
				State = 122; Match(T__1);
				State = 123; stmt();
				State = 124; Match(T__13);
				State = 125; stmt();
				}
				break;
			case 12:
				_localctx = new WhileContext(_localctx);
				EnterOuterAlt(_localctx, 12);
				{
				State = 127; Match(T__14);
				State = 128; Match(T__0);
				State = 129; expr(0);
				State = 130; Match(T__1);
				State = 131; stmt();
				}
				break;
			case 13:
				_localctx = new SExpContext(_localctx);
				EnterOuterAlt(_localctx, 13);
				{
				State = 133; expr(0);
				State = 134; Match(T__5);
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Type_Context : ParserRuleContext {
		public Type_Context(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_type_; } }
	 
		public Type_Context() { }
		public virtual void CopyFrom(Type_Context context) {
			base.CopyFrom(context);
		}
	}
	public partial class TTypeNameContext : Type_Context {
		public ITerminalNode ID() { return GetToken(LatteParser.ID, 0); }
		public TTypeNameContext(Type_Context context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.EnterTTypeName(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.ExitTTypeName(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ILatteVisitor<TResult> typedVisitor = visitor as ILatteVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitTTypeName(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Type_Context type_() {
		Type_Context _localctx = new Type_Context(Context, State);
		EnterRule(_localctx, 12, RULE_type_);
		try {
			_localctx = new TTypeNameContext(_localctx);
			EnterOuterAlt(_localctx, 1);
			{
			State = 138; Match(ID);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ItemContext : ParserRuleContext {
		public ITerminalNode ID() { return GetToken(LatteParser.ID, 0); }
		public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		public ItemContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_item; } }
		public override void EnterRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.EnterItem(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.ExitItem(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ILatteVisitor<TResult> typedVisitor = visitor as ILatteVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitItem(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ItemContext item() {
		ItemContext _localctx = new ItemContext(Context, State);
		EnterRule(_localctx, 14, RULE_item);
		try {
			State = 144;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,8,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 140; Match(ID);
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 141; Match(ID);
				State = 142; Match(T__7);
				State = 143; expr(0);
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ExprContext : ParserRuleContext {
		public ExprContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_expr; } }
	 
		public ExprContext() { }
		public virtual void CopyFrom(ExprContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class EIdContext : ExprContext {
		public ITerminalNode ID() { return GetToken(LatteParser.ID, 0); }
		public EIdContext(ExprContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.EnterEId(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.ExitEId(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ILatteVisitor<TResult> typedVisitor = visitor as ILatteVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitEId(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class EFunCallContext : ExprContext {
		public ITerminalNode ID() { return GetToken(LatteParser.ID, 0); }
		public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		public EFunCallContext(ExprContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.EnterEFunCall(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.ExitEFunCall(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ILatteVisitor<TResult> typedVisitor = visitor as ILatteVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitEFunCall(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class ERelOpContext : ExprContext {
		public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		public RelOpContext relOp() {
			return GetRuleContext<RelOpContext>(0);
		}
		public ERelOpContext(ExprContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.EnterERelOp(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.ExitERelOp(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ILatteVisitor<TResult> typedVisitor = visitor as ILatteVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitERelOp(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class ETrueContext : ExprContext {
		public ETrueContext(ExprContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.EnterETrue(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.ExitETrue(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ILatteVisitor<TResult> typedVisitor = visitor as ILatteVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitETrue(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class ECastContext : ExprContext {
		public Type_Context type_() {
			return GetRuleContext<Type_Context>(0);
		}
		public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		public ECastContext(ExprContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.EnterECast(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.ExitECast(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ILatteVisitor<TResult> typedVisitor = visitor as ILatteVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitECast(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class EOrContext : ExprContext {
		public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		public EOrContext(ExprContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.EnterEOr(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.ExitEOr(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ILatteVisitor<TResult> typedVisitor = visitor as ILatteVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitEOr(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class EIntContext : ExprContext {
		public ITerminalNode INT() { return GetToken(LatteParser.INT, 0); }
		public EIntContext(ExprContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.EnterEInt(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.ExitEInt(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ILatteVisitor<TResult> typedVisitor = visitor as ILatteVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitEInt(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class EUnOpContext : ExprContext {
		public UnOpContext unOp() {
			return GetRuleContext<UnOpContext>(0);
		}
		public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		public EUnOpContext(ExprContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.EnterEUnOp(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.ExitEUnOp(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ILatteVisitor<TResult> typedVisitor = visitor as ILatteVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitEUnOp(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class EStrContext : ExprContext {
		public ITerminalNode STR() { return GetToken(LatteParser.STR, 0); }
		public EStrContext(ExprContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.EnterEStr(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.ExitEStr(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ILatteVisitor<TResult> typedVisitor = visitor as ILatteVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitEStr(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class EMulOpContext : ExprContext {
		public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		public MulOpContext mulOp() {
			return GetRuleContext<MulOpContext>(0);
		}
		public EMulOpContext(ExprContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.EnterEMulOp(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.ExitEMulOp(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ILatteVisitor<TResult> typedVisitor = visitor as ILatteVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitEMulOp(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class EAndContext : ExprContext {
		public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		public EAndContext(ExprContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.EnterEAnd(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.ExitEAnd(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ILatteVisitor<TResult> typedVisitor = visitor as ILatteVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitEAnd(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class EObjectFieldContext : ExprContext {
		public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		public ITerminalNode ID() { return GetToken(LatteParser.ID, 0); }
		public EObjectFieldContext(ExprContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.EnterEObjectField(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.ExitEObjectField(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ILatteVisitor<TResult> typedVisitor = visitor as ILatteVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitEObjectField(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class EParenContext : ExprContext {
		public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		public EParenContext(ExprContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.EnterEParen(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.ExitEParen(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ILatteVisitor<TResult> typedVisitor = visitor as ILatteVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitEParen(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class EFalseContext : ExprContext {
		public EFalseContext(ExprContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.EnterEFalse(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.ExitEFalse(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ILatteVisitor<TResult> typedVisitor = visitor as ILatteVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitEFalse(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class EAddOpContext : ExprContext {
		public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		public AddOpContext addOp() {
			return GetRuleContext<AddOpContext>(0);
		}
		public EAddOpContext(ExprContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.EnterEAddOp(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.ExitEAddOp(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ILatteVisitor<TResult> typedVisitor = visitor as ILatteVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitEAddOp(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class ENullContext : ExprContext {
		public ENullContext(ExprContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.EnterENull(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.ExitENull(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ILatteVisitor<TResult> typedVisitor = visitor as ILatteVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitENull(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class ENewObjectContext : ExprContext {
		public ITerminalNode ID() { return GetToken(LatteParser.ID, 0); }
		public ENewObjectContext(ExprContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.EnterENewObject(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.ExitENewObject(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ILatteVisitor<TResult> typedVisitor = visitor as ILatteVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitENewObject(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ExprContext expr() {
		return expr(0);
	}

	private ExprContext expr(int _p) {
		ParserRuleContext _parentctx = Context;
		int _parentState = State;
		ExprContext _localctx = new ExprContext(Context, _parentState);
		ExprContext _prevctx = _localctx;
		int _startState = 16;
		EnterRecursionRule(_localctx, 16, RULE_expr, _p);
		int _la;
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 180;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,11,Context) ) {
			case 1:
				{
				_localctx = new EUnOpContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;

				State = 147; unOp();
				State = 148; expr(17);
				}
				break;
			case 2:
				{
				_localctx = new EIdContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 150; Match(ID);
				}
				break;
			case 3:
				{
				_localctx = new EIntContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 151; Match(INT);
				}
				break;
			case 4:
				{
				_localctx = new ETrueContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 152; Match(T__17);
				}
				break;
			case 5:
				{
				_localctx = new EFalseContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 153; Match(T__18);
				}
				break;
			case 6:
				{
				_localctx = new ENullContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 154; Match(T__19);
				}
				break;
			case 7:
				{
				_localctx = new ECastContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 155; Match(T__0);
				State = 156; type_();
				State = 157; Match(T__1);
				State = 158; expr(6);
				}
				break;
			case 8:
				{
				_localctx = new ENewObjectContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 160; Match(T__20);
				State = 161; Match(ID);
				}
				break;
			case 9:
				{
				_localctx = new EFunCallContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 162; Match(ID);
				State = 163; Match(T__0);
				State = 172;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << T__0) | (1L << T__17) | (1L << T__18) | (1L << T__19) | (1L << T__20) | (1L << T__21) | (1L << T__22) | (1L << INT) | (1L << ID) | (1L << STR))) != 0)) {
					{
					State = 164; expr(0);
					State = 169;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
					while (_la==T__6) {
						{
						{
						State = 165; Match(T__6);
						State = 166; expr(0);
						}
						}
						State = 171;
						ErrorHandler.Sync(this);
						_la = TokenStream.LA(1);
					}
					}
				}

				State = 174; Match(T__1);
				}
				break;
			case 10:
				{
				_localctx = new EStrContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 175; Match(STR);
				}
				break;
			case 11:
				{
				_localctx = new EParenContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 176; Match(T__0);
				State = 177; expr(0);
				State = 178; Match(T__1);
				}
				break;
			}
			Context.Stop = TokenStream.LT(-1);
			State = 205;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,13,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					if ( ParseListeners!=null )
						TriggerExitRuleEvent();
					_prevctx = _localctx;
					{
					State = 203;
					ErrorHandler.Sync(this);
					switch ( Interpreter.AdaptivePredict(TokenStream,12,Context) ) {
					case 1:
						{
						_localctx = new EMulOpContext(new ExprContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 182;
						if (!(Precpred(Context, 16))) throw new FailedPredicateException(this, "Precpred(Context, 16)");
						State = 183; mulOp();
						State = 184; expr(17);
						}
						break;
					case 2:
						{
						_localctx = new EAddOpContext(new ExprContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 186;
						if (!(Precpred(Context, 15))) throw new FailedPredicateException(this, "Precpred(Context, 15)");
						State = 187; addOp();
						State = 188; expr(16);
						}
						break;
					case 3:
						{
						_localctx = new ERelOpContext(new ExprContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 190;
						if (!(Precpred(Context, 14))) throw new FailedPredicateException(this, "Precpred(Context, 14)");
						State = 191; relOp();
						State = 192; expr(15);
						}
						break;
					case 4:
						{
						_localctx = new EAndContext(new ExprContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 194;
						if (!(Precpred(Context, 13))) throw new FailedPredicateException(this, "Precpred(Context, 13)");
						State = 195; Match(T__15);
						State = 196; expr(13);
						}
						break;
					case 5:
						{
						_localctx = new EOrContext(new ExprContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 197;
						if (!(Precpred(Context, 12))) throw new FailedPredicateException(this, "Precpred(Context, 12)");
						State = 198; Match(T__16);
						State = 199; expr(12);
						}
						break;
					case 6:
						{
						_localctx = new EObjectFieldContext(new ExprContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 200;
						if (!(Precpred(Context, 5))) throw new FailedPredicateException(this, "Precpred(Context, 5)");
						State = 201; Match(T__8);
						State = 202; Match(ID);
						}
						break;
					}
					} 
				}
				State = 207;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,13,Context);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			UnrollRecursionContexts(_parentctx);
		}
		return _localctx;
	}

	public partial class UnOpContext : ParserRuleContext {
		public UnOpContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_unOp; } }
	 
		public UnOpContext() { }
		public virtual void CopyFrom(UnOpContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class UnaryNegContext : UnOpContext {
		public UnaryNegContext(UnOpContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.EnterUnaryNeg(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.ExitUnaryNeg(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ILatteVisitor<TResult> typedVisitor = visitor as ILatteVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitUnaryNeg(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class UnaryMinusContext : UnOpContext {
		public UnaryMinusContext(UnOpContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.EnterUnaryMinus(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.ExitUnaryMinus(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ILatteVisitor<TResult> typedVisitor = visitor as ILatteVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitUnaryMinus(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public UnOpContext unOp() {
		UnOpContext _localctx = new UnOpContext(Context, State);
		EnterRule(_localctx, 18, RULE_unOp);
		try {
			State = 210;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case T__21:
				_localctx = new UnaryMinusContext(_localctx);
				EnterOuterAlt(_localctx, 1);
				{
				State = 208; Match(T__21);
				}
				break;
			case T__22:
				_localctx = new UnaryNegContext(_localctx);
				EnterOuterAlt(_localctx, 2);
				{
				State = 209; Match(T__22);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class AddOpContext : ParserRuleContext {
		public AddOpContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_addOp; } }
	 
		public AddOpContext() { }
		public virtual void CopyFrom(AddOpContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class PlusContext : AddOpContext {
		public PlusContext(AddOpContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.EnterPlus(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.ExitPlus(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ILatteVisitor<TResult> typedVisitor = visitor as ILatteVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPlus(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class MinusContext : AddOpContext {
		public MinusContext(AddOpContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.EnterMinus(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.ExitMinus(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ILatteVisitor<TResult> typedVisitor = visitor as ILatteVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitMinus(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public AddOpContext addOp() {
		AddOpContext _localctx = new AddOpContext(Context, State);
		EnterRule(_localctx, 20, RULE_addOp);
		try {
			State = 214;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case T__23:
				_localctx = new PlusContext(_localctx);
				EnterOuterAlt(_localctx, 1);
				{
				State = 212; Match(T__23);
				}
				break;
			case T__21:
				_localctx = new MinusContext(_localctx);
				EnterOuterAlt(_localctx, 2);
				{
				State = 213; Match(T__21);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class MulOpContext : ParserRuleContext {
		public MulOpContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_mulOp; } }
	 
		public MulOpContext() { }
		public virtual void CopyFrom(MulOpContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class DivideContext : MulOpContext {
		public DivideContext(MulOpContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.EnterDivide(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.ExitDivide(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ILatteVisitor<TResult> typedVisitor = visitor as ILatteVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitDivide(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class ModuloContext : MulOpContext {
		public ModuloContext(MulOpContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.EnterModulo(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.ExitModulo(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ILatteVisitor<TResult> typedVisitor = visitor as ILatteVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitModulo(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class MultiplyContext : MulOpContext {
		public MultiplyContext(MulOpContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.EnterMultiply(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.ExitMultiply(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ILatteVisitor<TResult> typedVisitor = visitor as ILatteVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitMultiply(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public MulOpContext mulOp() {
		MulOpContext _localctx = new MulOpContext(Context, State);
		EnterRule(_localctx, 22, RULE_mulOp);
		try {
			State = 219;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case T__24:
				_localctx = new MultiplyContext(_localctx);
				EnterOuterAlt(_localctx, 1);
				{
				State = 216; Match(T__24);
				}
				break;
			case T__25:
				_localctx = new DivideContext(_localctx);
				EnterOuterAlt(_localctx, 2);
				{
				State = 217; Match(T__25);
				}
				break;
			case T__26:
				_localctx = new ModuloContext(_localctx);
				EnterOuterAlt(_localctx, 3);
				{
				State = 218; Match(T__26);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class RelOpContext : ParserRuleContext {
		public RelOpContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_relOp; } }
	 
		public RelOpContext() { }
		public virtual void CopyFrom(RelOpContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class LessThanContext : RelOpContext {
		public LessThanContext(RelOpContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.EnterLessThan(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.ExitLessThan(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ILatteVisitor<TResult> typedVisitor = visitor as ILatteVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitLessThan(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class EqualsContext : RelOpContext {
		public EqualsContext(RelOpContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.EnterEquals(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.ExitEquals(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ILatteVisitor<TResult> typedVisitor = visitor as ILatteVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitEquals(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class GreaterEqualsContext : RelOpContext {
		public GreaterEqualsContext(RelOpContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.EnterGreaterEquals(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.ExitGreaterEquals(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ILatteVisitor<TResult> typedVisitor = visitor as ILatteVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitGreaterEquals(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class GreaterThanContext : RelOpContext {
		public GreaterThanContext(RelOpContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.EnterGreaterThan(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.ExitGreaterThan(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ILatteVisitor<TResult> typedVisitor = visitor as ILatteVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitGreaterThan(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class LessEqualsContext : RelOpContext {
		public LessEqualsContext(RelOpContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.EnterLessEquals(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.ExitLessEquals(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ILatteVisitor<TResult> typedVisitor = visitor as ILatteVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitLessEquals(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class NotEqualsContext : RelOpContext {
		public NotEqualsContext(RelOpContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.EnterNotEquals(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.ExitNotEquals(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ILatteVisitor<TResult> typedVisitor = visitor as ILatteVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitNotEquals(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public RelOpContext relOp() {
		RelOpContext _localctx = new RelOpContext(Context, State);
		EnterRule(_localctx, 24, RULE_relOp);
		try {
			State = 227;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case T__27:
				_localctx = new LessThanContext(_localctx);
				EnterOuterAlt(_localctx, 1);
				{
				State = 221; Match(T__27);
				}
				break;
			case T__28:
				_localctx = new LessEqualsContext(_localctx);
				EnterOuterAlt(_localctx, 2);
				{
				State = 222; Match(T__28);
				}
				break;
			case T__29:
				_localctx = new GreaterThanContext(_localctx);
				EnterOuterAlt(_localctx, 3);
				{
				State = 223; Match(T__29);
				}
				break;
			case T__30:
				_localctx = new GreaterEqualsContext(_localctx);
				EnterOuterAlt(_localctx, 4);
				{
				State = 224; Match(T__30);
				}
				break;
			case T__31:
				_localctx = new EqualsContext(_localctx);
				EnterOuterAlt(_localctx, 5);
				{
				State = 225; Match(T__31);
				}
				break;
			case T__32:
				_localctx = new NotEqualsContext(_localctx);
				EnterOuterAlt(_localctx, 6);
				{
				State = 226; Match(T__32);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public override bool Sempred(RuleContext _localctx, int ruleIndex, int predIndex) {
		switch (ruleIndex) {
		case 8: return expr_sempred((ExprContext)_localctx, predIndex);
		}
		return true;
	}
	private bool expr_sempred(ExprContext _localctx, int predIndex) {
		switch (predIndex) {
		case 0: return Precpred(Context, 16);
		case 1: return Precpred(Context, 15);
		case 2: return Precpred(Context, 14);
		case 3: return Precpred(Context, 13);
		case 4: return Precpred(Context, 12);
		case 5: return Precpred(Context, 5);
		}
		return true;
	}

	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x3', ')', '\xE8', '\x4', '\x2', '\t', '\x2', '\x4', '\x3', 
		'\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', '\x5', '\x4', 
		'\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', '\t', '\b', 
		'\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', '\t', '\v', 
		'\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', '\t', 
		'\xE', '\x3', '\x2', '\x6', '\x2', '\x1E', '\n', '\x2', '\r', '\x2', '\xE', 
		'\x2', '\x1F', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', 
		'\x5', '\x3', '&', '\n', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', 
		'\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\a', '\x3', '/', 
		'\n', '\x3', '\f', '\x3', '\xE', '\x3', '\x32', '\v', '\x3', '\x3', '\x3', 
		'\x5', '\x3', '\x35', '\n', '\x3', '\x3', '\x4', '\x3', '\x4', '\x3', 
		'\x4', '\x3', '\x4', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', 
		'\x5', '\x3', '\x5', '\x3', '\x5', '\a', '\x5', '\x41', '\n', '\x5', '\f', 
		'\x5', '\xE', '\x5', '\x44', '\v', '\x5', '\x3', '\x6', '\x3', '\x6', 
		'\a', '\x6', 'H', '\n', '\x6', '\f', '\x6', '\xE', '\x6', 'K', '\v', '\x6', 
		'\x3', '\x6', '\x3', '\x6', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', 
		'\a', '\x3', '\a', '\x3', '\a', '\a', '\a', 'U', '\n', '\a', '\f', '\a', 
		'\xE', '\a', 'X', '\v', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', 
		'\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', 
		'\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', 
		'\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', 
		'\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', 
		'\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', 
		'\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', 
		'\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', 
		'\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', 
		'\a', '\x3', '\a', '\x5', '\a', '\x8B', '\n', '\a', '\x3', '\b', '\x3', 
		'\b', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x5', '\t', 
		'\x93', '\n', '\t', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', 
		'\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', 
		'\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', 
		'\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', 
		'\n', '\a', '\n', '\xAA', '\n', '\n', '\f', '\n', '\xE', '\n', '\xAD', 
		'\v', '\n', '\x5', '\n', '\xAF', '\n', '\n', '\x3', '\n', '\x3', '\n', 
		'\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x5', '\n', '\xB7', 
		'\n', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', 
		'\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', 
		'\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', 
		'\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', 
		'\a', '\n', '\xCE', '\n', '\n', '\f', '\n', '\xE', '\n', '\xD1', '\v', 
		'\n', '\x3', '\v', '\x3', '\v', '\x5', '\v', '\xD5', '\n', '\v', '\x3', 
		'\f', '\x3', '\f', '\x5', '\f', '\xD9', '\n', '\f', '\x3', '\r', '\x3', 
		'\r', '\x3', '\r', '\x5', '\r', '\xDE', '\n', '\r', '\x3', '\xE', '\x3', 
		'\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x5', 
		'\xE', '\xE6', '\n', '\xE', '\x3', '\xE', '\x2', '\x3', '\x12', '\xF', 
		'\x2', '\x4', '\x6', '\b', '\n', '\f', '\xE', '\x10', '\x12', '\x14', 
		'\x16', '\x18', '\x1A', '\x2', '\x2', '\x2', '\x109', '\x2', '\x1D', '\x3', 
		'\x2', '\x2', '\x2', '\x4', '\x34', '\x3', '\x2', '\x2', '\x2', '\x6', 
		'\x36', '\x3', '\x2', '\x2', '\x2', '\b', ':', '\x3', '\x2', '\x2', '\x2', 
		'\n', '\x45', '\x3', '\x2', '\x2', '\x2', '\f', '\x8A', '\x3', '\x2', 
		'\x2', '\x2', '\xE', '\x8C', '\x3', '\x2', '\x2', '\x2', '\x10', '\x92', 
		'\x3', '\x2', '\x2', '\x2', '\x12', '\xB6', '\x3', '\x2', '\x2', '\x2', 
		'\x14', '\xD4', '\x3', '\x2', '\x2', '\x2', '\x16', '\xD8', '\x3', '\x2', 
		'\x2', '\x2', '\x18', '\xDD', '\x3', '\x2', '\x2', '\x2', '\x1A', '\xE5', 
		'\x3', '\x2', '\x2', '\x2', '\x1C', '\x1E', '\x5', '\x4', '\x3', '\x2', 
		'\x1D', '\x1C', '\x3', '\x2', '\x2', '\x2', '\x1E', '\x1F', '\x3', '\x2', 
		'\x2', '\x2', '\x1F', '\x1D', '\x3', '\x2', '\x2', '\x2', '\x1F', ' ', 
		'\x3', '\x2', '\x2', '\x2', ' ', '\x3', '\x3', '\x2', '\x2', '\x2', '!', 
		'\"', '\x5', '\xE', '\b', '\x2', '\"', '#', '\a', '\'', '\x2', '\x2', 
		'#', '%', '\a', '\x3', '\x2', '\x2', '$', '&', '\x5', '\b', '\x5', '\x2', 
		'%', '$', '\x3', '\x2', '\x2', '\x2', '%', '&', '\x3', '\x2', '\x2', '\x2', 
		'&', '\'', '\x3', '\x2', '\x2', '\x2', '\'', '(', '\a', '\x4', '\x2', 
		'\x2', '(', ')', '\x5', '\n', '\x6', '\x2', ')', '\x35', '\x3', '\x2', 
		'\x2', '\x2', '*', '+', '\a', '\x5', '\x2', '\x2', '+', ',', '\a', '\'', 
		'\x2', '\x2', ',', '\x30', '\a', '\x6', '\x2', '\x2', '-', '/', '\x5', 
		'\x6', '\x4', '\x2', '.', '-', '\x3', '\x2', '\x2', '\x2', '/', '\x32', 
		'\x3', '\x2', '\x2', '\x2', '\x30', '.', '\x3', '\x2', '\x2', '\x2', '\x30', 
		'\x31', '\x3', '\x2', '\x2', '\x2', '\x31', '\x33', '\x3', '\x2', '\x2', 
		'\x2', '\x32', '\x30', '\x3', '\x2', '\x2', '\x2', '\x33', '\x35', '\a', 
		'\a', '\x2', '\x2', '\x34', '!', '\x3', '\x2', '\x2', '\x2', '\x34', '*', 
		'\x3', '\x2', '\x2', '\x2', '\x35', '\x5', '\x3', '\x2', '\x2', '\x2', 
		'\x36', '\x37', '\x5', '\xE', '\b', '\x2', '\x37', '\x38', '\a', '\'', 
		'\x2', '\x2', '\x38', '\x39', '\a', '\b', '\x2', '\x2', '\x39', '\a', 
		'\x3', '\x2', '\x2', '\x2', ':', ';', '\x5', '\xE', '\b', '\x2', ';', 
		'\x42', '\a', '\'', '\x2', '\x2', '<', '=', '\a', '\t', '\x2', '\x2', 
		'=', '>', '\x5', '\xE', '\b', '\x2', '>', '?', '\a', '\'', '\x2', '\x2', 
		'?', '\x41', '\x3', '\x2', '\x2', '\x2', '@', '<', '\x3', '\x2', '\x2', 
		'\x2', '\x41', '\x44', '\x3', '\x2', '\x2', '\x2', '\x42', '@', '\x3', 
		'\x2', '\x2', '\x2', '\x42', '\x43', '\x3', '\x2', '\x2', '\x2', '\x43', 
		'\t', '\x3', '\x2', '\x2', '\x2', '\x44', '\x42', '\x3', '\x2', '\x2', 
		'\x2', '\x45', 'I', '\a', '\x6', '\x2', '\x2', '\x46', 'H', '\x5', '\f', 
		'\a', '\x2', 'G', '\x46', '\x3', '\x2', '\x2', '\x2', 'H', 'K', '\x3', 
		'\x2', '\x2', '\x2', 'I', 'G', '\x3', '\x2', '\x2', '\x2', 'I', 'J', '\x3', 
		'\x2', '\x2', '\x2', 'J', 'L', '\x3', '\x2', '\x2', '\x2', 'K', 'I', '\x3', 
		'\x2', '\x2', '\x2', 'L', 'M', '\a', '\a', '\x2', '\x2', 'M', '\v', '\x3', 
		'\x2', '\x2', '\x2', 'N', '\x8B', '\a', '\b', '\x2', '\x2', 'O', '\x8B', 
		'\x5', '\n', '\x6', '\x2', 'P', 'Q', '\x5', '\xE', '\b', '\x2', 'Q', 'V', 
		'\x5', '\x10', '\t', '\x2', 'R', 'S', '\a', '\t', '\x2', '\x2', 'S', 'U', 
		'\x5', '\x10', '\t', '\x2', 'T', 'R', '\x3', '\x2', '\x2', '\x2', 'U', 
		'X', '\x3', '\x2', '\x2', '\x2', 'V', 'T', '\x3', '\x2', '\x2', '\x2', 
		'V', 'W', '\x3', '\x2', '\x2', '\x2', 'W', 'Y', '\x3', '\x2', '\x2', '\x2', 
		'X', 'V', '\x3', '\x2', '\x2', '\x2', 'Y', 'Z', '\a', '\b', '\x2', '\x2', 
		'Z', '\x8B', '\x3', '\x2', '\x2', '\x2', '[', '\\', '\a', '\'', '\x2', 
		'\x2', '\\', ']', '\a', '\n', '\x2', '\x2', ']', '^', '\x5', '\x12', '\n', 
		'\x2', '^', '_', '\a', '\b', '\x2', '\x2', '_', '\x8B', '\x3', '\x2', 
		'\x2', '\x2', '`', '\x61', '\x5', '\x12', '\n', '\x2', '\x61', '\x62', 
		'\a', '\v', '\x2', '\x2', '\x62', '\x63', '\a', '\'', '\x2', '\x2', '\x63', 
		'\x64', '\a', '\n', '\x2', '\x2', '\x64', '\x65', '\x5', '\x12', '\n', 
		'\x2', '\x65', '\x66', '\a', '\b', '\x2', '\x2', '\x66', '\x8B', '\x3', 
		'\x2', '\x2', '\x2', 'g', 'h', '\a', '\'', '\x2', '\x2', 'h', 'i', '\a', 
		'\f', '\x2', '\x2', 'i', '\x8B', '\a', '\b', '\x2', '\x2', 'j', 'k', '\a', 
		'\'', '\x2', '\x2', 'k', 'l', '\a', '\r', '\x2', '\x2', 'l', '\x8B', '\a', 
		'\b', '\x2', '\x2', 'm', 'n', '\a', '\xE', '\x2', '\x2', 'n', 'o', '\x5', 
		'\x12', '\n', '\x2', 'o', 'p', '\a', '\b', '\x2', '\x2', 'p', '\x8B', 
		'\x3', '\x2', '\x2', '\x2', 'q', 'r', '\a', '\xE', '\x2', '\x2', 'r', 
		'\x8B', '\a', '\b', '\x2', '\x2', 's', 't', '\a', '\xF', '\x2', '\x2', 
		't', 'u', '\a', '\x3', '\x2', '\x2', 'u', 'v', '\x5', '\x12', '\n', '\x2', 
		'v', 'w', '\a', '\x4', '\x2', '\x2', 'w', 'x', '\x5', '\f', '\a', '\x2', 
		'x', '\x8B', '\x3', '\x2', '\x2', '\x2', 'y', 'z', '\a', '\xF', '\x2', 
		'\x2', 'z', '{', '\a', '\x3', '\x2', '\x2', '{', '|', '\x5', '\x12', '\n', 
		'\x2', '|', '}', '\a', '\x4', '\x2', '\x2', '}', '~', '\x5', '\f', '\a', 
		'\x2', '~', '\x7F', '\a', '\x10', '\x2', '\x2', '\x7F', '\x80', '\x5', 
		'\f', '\a', '\x2', '\x80', '\x8B', '\x3', '\x2', '\x2', '\x2', '\x81', 
		'\x82', '\a', '\x11', '\x2', '\x2', '\x82', '\x83', '\a', '\x3', '\x2', 
		'\x2', '\x83', '\x84', '\x5', '\x12', '\n', '\x2', '\x84', '\x85', '\a', 
		'\x4', '\x2', '\x2', '\x85', '\x86', '\x5', '\f', '\a', '\x2', '\x86', 
		'\x8B', '\x3', '\x2', '\x2', '\x2', '\x87', '\x88', '\x5', '\x12', '\n', 
		'\x2', '\x88', '\x89', '\a', '\b', '\x2', '\x2', '\x89', '\x8B', '\x3', 
		'\x2', '\x2', '\x2', '\x8A', 'N', '\x3', '\x2', '\x2', '\x2', '\x8A', 
		'O', '\x3', '\x2', '\x2', '\x2', '\x8A', 'P', '\x3', '\x2', '\x2', '\x2', 
		'\x8A', '[', '\x3', '\x2', '\x2', '\x2', '\x8A', '`', '\x3', '\x2', '\x2', 
		'\x2', '\x8A', 'g', '\x3', '\x2', '\x2', '\x2', '\x8A', 'j', '\x3', '\x2', 
		'\x2', '\x2', '\x8A', 'm', '\x3', '\x2', '\x2', '\x2', '\x8A', 'q', '\x3', 
		'\x2', '\x2', '\x2', '\x8A', 's', '\x3', '\x2', '\x2', '\x2', '\x8A', 
		'y', '\x3', '\x2', '\x2', '\x2', '\x8A', '\x81', '\x3', '\x2', '\x2', 
		'\x2', '\x8A', '\x87', '\x3', '\x2', '\x2', '\x2', '\x8B', '\r', '\x3', 
		'\x2', '\x2', '\x2', '\x8C', '\x8D', '\a', '\'', '\x2', '\x2', '\x8D', 
		'\xF', '\x3', '\x2', '\x2', '\x2', '\x8E', '\x93', '\a', '\'', '\x2', 
		'\x2', '\x8F', '\x90', '\a', '\'', '\x2', '\x2', '\x90', '\x91', '\a', 
		'\n', '\x2', '\x2', '\x91', '\x93', '\x5', '\x12', '\n', '\x2', '\x92', 
		'\x8E', '\x3', '\x2', '\x2', '\x2', '\x92', '\x8F', '\x3', '\x2', '\x2', 
		'\x2', '\x93', '\x11', '\x3', '\x2', '\x2', '\x2', '\x94', '\x95', '\b', 
		'\n', '\x1', '\x2', '\x95', '\x96', '\x5', '\x14', '\v', '\x2', '\x96', 
		'\x97', '\x5', '\x12', '\n', '\x13', '\x97', '\xB7', '\x3', '\x2', '\x2', 
		'\x2', '\x98', '\xB7', '\a', '\'', '\x2', '\x2', '\x99', '\xB7', '\a', 
		'&', '\x2', '\x2', '\x9A', '\xB7', '\a', '\x14', '\x2', '\x2', '\x9B', 
		'\xB7', '\a', '\x15', '\x2', '\x2', '\x9C', '\xB7', '\a', '\x16', '\x2', 
		'\x2', '\x9D', '\x9E', '\a', '\x3', '\x2', '\x2', '\x9E', '\x9F', '\x5', 
		'\xE', '\b', '\x2', '\x9F', '\xA0', '\a', '\x4', '\x2', '\x2', '\xA0', 
		'\xA1', '\x5', '\x12', '\n', '\b', '\xA1', '\xB7', '\x3', '\x2', '\x2', 
		'\x2', '\xA2', '\xA3', '\a', '\x17', '\x2', '\x2', '\xA3', '\xB7', '\a', 
		'\'', '\x2', '\x2', '\xA4', '\xA5', '\a', '\'', '\x2', '\x2', '\xA5', 
		'\xAE', '\a', '\x3', '\x2', '\x2', '\xA6', '\xAB', '\x5', '\x12', '\n', 
		'\x2', '\xA7', '\xA8', '\a', '\t', '\x2', '\x2', '\xA8', '\xAA', '\x5', 
		'\x12', '\n', '\x2', '\xA9', '\xA7', '\x3', '\x2', '\x2', '\x2', '\xAA', 
		'\xAD', '\x3', '\x2', '\x2', '\x2', '\xAB', '\xA9', '\x3', '\x2', '\x2', 
		'\x2', '\xAB', '\xAC', '\x3', '\x2', '\x2', '\x2', '\xAC', '\xAF', '\x3', 
		'\x2', '\x2', '\x2', '\xAD', '\xAB', '\x3', '\x2', '\x2', '\x2', '\xAE', 
		'\xA6', '\x3', '\x2', '\x2', '\x2', '\xAE', '\xAF', '\x3', '\x2', '\x2', 
		'\x2', '\xAF', '\xB0', '\x3', '\x2', '\x2', '\x2', '\xB0', '\xB7', '\a', 
		'\x4', '\x2', '\x2', '\xB1', '\xB7', '\a', ')', '\x2', '\x2', '\xB2', 
		'\xB3', '\a', '\x3', '\x2', '\x2', '\xB3', '\xB4', '\x5', '\x12', '\n', 
		'\x2', '\xB4', '\xB5', '\a', '\x4', '\x2', '\x2', '\xB5', '\xB7', '\x3', 
		'\x2', '\x2', '\x2', '\xB6', '\x94', '\x3', '\x2', '\x2', '\x2', '\xB6', 
		'\x98', '\x3', '\x2', '\x2', '\x2', '\xB6', '\x99', '\x3', '\x2', '\x2', 
		'\x2', '\xB6', '\x9A', '\x3', '\x2', '\x2', '\x2', '\xB6', '\x9B', '\x3', 
		'\x2', '\x2', '\x2', '\xB6', '\x9C', '\x3', '\x2', '\x2', '\x2', '\xB6', 
		'\x9D', '\x3', '\x2', '\x2', '\x2', '\xB6', '\xA2', '\x3', '\x2', '\x2', 
		'\x2', '\xB6', '\xA4', '\x3', '\x2', '\x2', '\x2', '\xB6', '\xB1', '\x3', 
		'\x2', '\x2', '\x2', '\xB6', '\xB2', '\x3', '\x2', '\x2', '\x2', '\xB7', 
		'\xCF', '\x3', '\x2', '\x2', '\x2', '\xB8', '\xB9', '\f', '\x12', '\x2', 
		'\x2', '\xB9', '\xBA', '\x5', '\x18', '\r', '\x2', '\xBA', '\xBB', '\x5', 
		'\x12', '\n', '\x13', '\xBB', '\xCE', '\x3', '\x2', '\x2', '\x2', '\xBC', 
		'\xBD', '\f', '\x11', '\x2', '\x2', '\xBD', '\xBE', '\x5', '\x16', '\f', 
		'\x2', '\xBE', '\xBF', '\x5', '\x12', '\n', '\x12', '\xBF', '\xCE', '\x3', 
		'\x2', '\x2', '\x2', '\xC0', '\xC1', '\f', '\x10', '\x2', '\x2', '\xC1', 
		'\xC2', '\x5', '\x1A', '\xE', '\x2', '\xC2', '\xC3', '\x5', '\x12', '\n', 
		'\x11', '\xC3', '\xCE', '\x3', '\x2', '\x2', '\x2', '\xC4', '\xC5', '\f', 
		'\xF', '\x2', '\x2', '\xC5', '\xC6', '\a', '\x12', '\x2', '\x2', '\xC6', 
		'\xCE', '\x5', '\x12', '\n', '\xF', '\xC7', '\xC8', '\f', '\xE', '\x2', 
		'\x2', '\xC8', '\xC9', '\a', '\x13', '\x2', '\x2', '\xC9', '\xCE', '\x5', 
		'\x12', '\n', '\xE', '\xCA', '\xCB', '\f', '\a', '\x2', '\x2', '\xCB', 
		'\xCC', '\a', '\v', '\x2', '\x2', '\xCC', '\xCE', '\a', '\'', '\x2', '\x2', 
		'\xCD', '\xB8', '\x3', '\x2', '\x2', '\x2', '\xCD', '\xBC', '\x3', '\x2', 
		'\x2', '\x2', '\xCD', '\xC0', '\x3', '\x2', '\x2', '\x2', '\xCD', '\xC4', 
		'\x3', '\x2', '\x2', '\x2', '\xCD', '\xC7', '\x3', '\x2', '\x2', '\x2', 
		'\xCD', '\xCA', '\x3', '\x2', '\x2', '\x2', '\xCE', '\xD1', '\x3', '\x2', 
		'\x2', '\x2', '\xCF', '\xCD', '\x3', '\x2', '\x2', '\x2', '\xCF', '\xD0', 
		'\x3', '\x2', '\x2', '\x2', '\xD0', '\x13', '\x3', '\x2', '\x2', '\x2', 
		'\xD1', '\xCF', '\x3', '\x2', '\x2', '\x2', '\xD2', '\xD5', '\a', '\x18', 
		'\x2', '\x2', '\xD3', '\xD5', '\a', '\x19', '\x2', '\x2', '\xD4', '\xD2', 
		'\x3', '\x2', '\x2', '\x2', '\xD4', '\xD3', '\x3', '\x2', '\x2', '\x2', 
		'\xD5', '\x15', '\x3', '\x2', '\x2', '\x2', '\xD6', '\xD9', '\a', '\x1A', 
		'\x2', '\x2', '\xD7', '\xD9', '\a', '\x18', '\x2', '\x2', '\xD8', '\xD6', 
		'\x3', '\x2', '\x2', '\x2', '\xD8', '\xD7', '\x3', '\x2', '\x2', '\x2', 
		'\xD9', '\x17', '\x3', '\x2', '\x2', '\x2', '\xDA', '\xDE', '\a', '\x1B', 
		'\x2', '\x2', '\xDB', '\xDE', '\a', '\x1C', '\x2', '\x2', '\xDC', '\xDE', 
		'\a', '\x1D', '\x2', '\x2', '\xDD', '\xDA', '\x3', '\x2', '\x2', '\x2', 
		'\xDD', '\xDB', '\x3', '\x2', '\x2', '\x2', '\xDD', '\xDC', '\x3', '\x2', 
		'\x2', '\x2', '\xDE', '\x19', '\x3', '\x2', '\x2', '\x2', '\xDF', '\xE6', 
		'\a', '\x1E', '\x2', '\x2', '\xE0', '\xE6', '\a', '\x1F', '\x2', '\x2', 
		'\xE1', '\xE6', '\a', ' ', '\x2', '\x2', '\xE2', '\xE6', '\a', '!', '\x2', 
		'\x2', '\xE3', '\xE6', '\a', '\"', '\x2', '\x2', '\xE4', '\xE6', '\a', 
		'#', '\x2', '\x2', '\xE5', '\xDF', '\x3', '\x2', '\x2', '\x2', '\xE5', 
		'\xE0', '\x3', '\x2', '\x2', '\x2', '\xE5', '\xE1', '\x3', '\x2', '\x2', 
		'\x2', '\xE5', '\xE2', '\x3', '\x2', '\x2', '\x2', '\xE5', '\xE3', '\x3', 
		'\x2', '\x2', '\x2', '\xE5', '\xE4', '\x3', '\x2', '\x2', '\x2', '\xE6', 
		'\x1B', '\x3', '\x2', '\x2', '\x2', '\x14', '\x1F', '%', '\x30', '\x34', 
		'\x42', 'I', 'V', '\x8A', '\x92', '\xAB', '\xAE', '\xB6', '\xCD', '\xCF', 
		'\xD4', '\xD8', '\xDD', '\xE5',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
} // namespace LatteAntlr
